title: Nihil Kottal
logo: /Assets/Headshot.jpg
description: Passionate Data Scientist leveraging curiosity and analytical prowess to solve complex challenges and drive innovation
Area of Expertise: 
  - Machine Learning
  - Data Analysis
  - Natural Language Processing
  - Fraud Analytics
  - Big Data Algorithms
  - Time Series Forecasting
show_downloads: False
theme: jekyll-theme-Minimal
