title: Nihil Kottal
logo: /Assets/Headshot.jpg
description: >
  I am deeply passionate about data science, especially in the realms of E-Commerce and Fraud Analytics.
  My curiosity drives me to embrace challenges, using my analytical skills and science background to innovate and solve problems from multiple perspectives.

  I specialize in leveraging advanced data analysis, machine learning, and statistical modeling to drive insights in E-Commerce and Fraud Detection. My expertise includes anomaly detection, customer behavior analysis, and predictive modeling to enhance business decision-making.
show_downloads: False
theme: jekyll-theme-Minimal
