title: Nihil Kottal
logo: /Assets/Headshot.jpg
description: Passionate Data Scientist leveraging curiosity and analytical prowess to solve complex challenges and drive innovation
show_downloads: True
theme: jekyll-theme-Minimal
