title: Nihil Kottal
show_downloads: true
description: I am deeply passionate about data science, driven by an insatiable curiosity and a keen analytical mind. My background in science equips me to approach complex challenges from unique perspectives, allowing me to innovate and develop effective solutions.
theme: jekyll-theme-minimal
