title: Nihil Kottal
#logo: /Assets/Headshot.jpg
#description: Data Scientist passionate about leveraging curiosity and analytical prowess to solve complex challenges and drive innovation
show_downloads: False
theme: jekyll-theme-minimal
