title: Nihil Kottal
logo: /Assets/Headshot.jpg
description: >
  I am a data-driven professional passionate about leveraging AI-powered analytics to drive strategic business decisions. With a strong foundation in data science and a proven ability to navigate ambiguity, I thrive on solving complex data challenges in fast-paced, evolving environments. My expertise lies in translating business needs into actionable insights using tools like SQL, Power BI, and advanced analytical techniques.<br><br>

  I’m especially excited about the opportunity to lead transformative projects that harness artificial intelligence to uncover patterns, optimize processes, and deliver measurable impact.<br><br>

  If you’re seeking a  Data Analyst who combines technical depth with a visionary approach to data strategy and enablement, let’s connect.

show_downloads: False
theme: jekyll-theme-Minimal
